platform :ios, '12.0'

target 'DJISDKSwiftDemo' do
   # pod 'DJI-SDK-iOS', '~> 4.13.1'
   pod 'DJI-SDK-iOS', '~> 4.14-trial1'
   # pod 'DJIWidget', '~> 1.6.3'
   pod 'DJIWidget', '~> 1.6.4'
   pod 'DJIFlySafeDatabaseResource', '~> 01.00.01.17'
end
